PACKAGE_NAME="idpf"
PACKAGE_VERSION="0.0.653"
AUTOINSTALL="yes"

MAKE[0]="'make' -j $(nproc) KERNEL_UNAME=${kernelver} compile"
BUILT_MODULE_NAME[0]="idpf"
BUILT_MODULE_LOCATION[0]="idpf/src/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/ethernet/intel/"

